# Generated by Django 4.2.2 on 2023-06-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('image', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'post_view',
                'managed': False,
            },
        ),
    ]
