# Generated by Django 4.2.2 on 2023-06-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_postview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
